# Usa la imagen oficial de RabbitMQ desde Docker Hub
FROM rabbitmq:3.8

# Habilita el complemento de gestión de RabbitMQ
RUN rabbitmq-plugins enable rabbitmq_management
RUN rabbitmqctl add_queue cola1